apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: je12zo02z-nodejs
  janus-idp.io/tekton: je12zo02z-nodejs
  backstage.io/kubernetes-id: je12zo02z-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: je12zo02z-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
