apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: je12zo02z-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: je12zo02z-nodejs 
  name: je12zo02z-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: je12zo02z-nodejs 
